spring.application.name=ToDo

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.drop-first=false

logging.level.liquibase=DEBUG
logging.level.liquibase.changelog=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

jwt_secret=SECRET

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.properties.spring.json.add.type.headers=false

#logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.cloud.aws.s3.endpoint=http://localhost:9000
spring.cloud.aws.s3.region=us-east-1
spring.cloud.aws.s3.path-style-access=true

spring.cloud.aws.credentials.access-key=minioadmin
spring.cloud.aws.credentials.secret-key=minioadmin

spring.cloud.aws.stack.auto=false

app.storage.bucket-name=tasks

spring.data.mongodb.uri=mongodb://localhost:27017/todo_db
spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=danilvigerin65@gmail.com
spring.mail.username=tasktrackersuppport@gmail.com
spring.mail.password=vbyw ftoa ovso lelv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.password-reset.token-expiration-minutes=30

spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

video.meetings.cleanup-after-days=4

# Actuator configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.distribution.percentiles-histogram.jvm.gc.pause=true
management.metrics.enable.redis=true
management.metrics.enable.mongodb=true
management.metrics.enable.kafka=true
management.metrics.enable.jvm=true
management.metrics.enable.logback=true
management.metrics.enable.hikaricp=true
management.metrics.enable.http=true
management.metrics.enable.system=true
management.server.port=8080


management.metrics.tags.application=${spring.application.name}
management.metrics.tags.instance=${HOSTNAME:localhost}
management.metrics.tags.environment=local


spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=false

